version: 2.1
orbs:
  cypress: cypress-io/cypress@2
jobs:
  release:
    executor: cypress/browsers-chrome99-ff97
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run semantic-release

workflows:
  build:
    jobs:
      - cypress/install:
          name: Install
          executor: cypress/browsers-chrome99-ff97

      - cypress/run:
          name: Electron tests
          requires:
            - Install
          executor: cypress/browsers-chrome99-ff97
          install-command: echo 'Nothing to install in this job'
          no-workspace: true

      - cypress/run:
          name: Chrome tests
          requires:
            - Install
          executor: cypress/browsers-chrome99-ff97
          browser: chrome
          install-command: echo 'Nothing to install in this job'
          no-workspace: true

      - cypress/run:
          name: Firefox tests
          requires:
            - Install
          executor: cypress/browsers-chrome99-ff97
          browser: firefox
          install-command: echo 'Nothing to install in this job'
          no-workspace: true

      - release:
          requires:
            - Electron tests
            - Chrome tests
            - Firefox tests
